# Generated by Django 4.1.5 on 2023-02-01 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('state', models.CharField(choices=[('proposal', 'Proposal'), ('signed', 'Signed'), ('canceled', 'Canceled')], default='proposal', max_length=255, verbose_name='State')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature Date')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('address', models.TextField(blank=True, max_length=1080, verbose_name='Address')),
                ('prospect', models.BooleanField(verbose_name='Prospect')),
                ('phone_number', models.CharField(blank=True, max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Event Date')),
                ('address', models.TextField(blank=True, max_length=1080, verbose_name='Address')),
                ('state', models.CharField(choices=[('to_plan', 'To Plan'), ('planned', 'Planned'), ('done', 'Done'), ('canceled', 'Canceled')], default='proposal', max_length=255, verbose_name='State')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_management.contract', verbose_name='Contract')),
                ('event_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_to_manage', to='event_management.employee', verbose_name='Event Employee')),
                ('support_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_to_support', to='event_management.employee', verbose_name='Support Employee')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='event_management.customer', verbose_name='Customer'),
        ),
    ]
