# Generated by Django 4.1.5 on 2023-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_customer_time_created_customer_time_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=555, verbose_name='Name'),
        ),
    ]
