# Generated by Django 4.1.5 on 2023-03-28 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_management', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Due'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sale_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_managed', to=settings.AUTH_USER_MODEL, verbose_name='Sales Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default="Amazon", max_length=555,
                                   verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Jean', max_length=555, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sale_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_managed', to=settings.AUTH_USER_MODEL, verbose_name='Sales Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attendees'),
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_management.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=555, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='Phone'),
        ),
    ]
