# Generated by Django 4.1.5 on 2023-03-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_contract_amount_contract_payment_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_employee',
        ),
    ]
